version: '3.8'
services:
  poll:
    build: ./poll
    restart: always
    networks:
      - poll-tier
    ports:
      - 5000:80
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    restart: always
    networks:
      - back-tier

  db:
    image: postgres:latest
    restart: always
    networks:
      - result-tier
      - back-tier
    volumes:
    - db-data:/var/lib/postgresql/data
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  result:
    build: ./result
    restart: always
    ports:
      - "5001:80"
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: